# Please note we are using Docker Compose version 3
version: '3'
services:
    DC1N1:
        image: joseenrique/cassandra
        volumes:
            - ./n1data:/var/lib/cassandra
        environment:
            - CASSANDRA_CLUSTERNAME=dev_cluster
            - CASSANDRA_TOKEN=256
            - CASSANDRA_SEEDS=192.168.2.105
            - CASSANDRA_BROADCAST=192.168.2.105
            - CASSANDRA_SNITCH=GossipingPropertyFileSnitch
            - CASSANDRA_AUTH=PasswordAuthenticator
        expose:
            - 7000
            - 7001
            - 7199
            - 9042
            - 9160
        ports:
          - 7000:7000
          - 7001:7001
          - 7199:7199
          - 9042:9042
          - 9160:9160

        ulimits:
            memlock: -1
            nproc: 32768
            nofile: 100000
